services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC

  identity.api:
    build:
      context: ..
      dockerfile: deploy/webapi.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - rabbitmq
      - jaeger
    ports:
      - "8080:8080"
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests

volumes:
  pgdata:
